[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "text/html; charset=UTF-8"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=UTF-8"

[[headers]]
  for = "/*.jsx"
  [headers.values]
    Content-Type = "text/javascript; charset=UTF-8"

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "dist"
  command = "npm run build"